### ISSUE TITLE
Most clients support gzip, compare gzipped file sizes over time

### ISSUE THREAD

**Issue by eliotsykes** [ilkkao/ember-size-tracker#3]
Gzipped files are more representative of what the size of the final payload delivered to clients will be. 

I'm not making this claim, but its plausible that:
- un-gzipped ember.min.js from today is larger than an un-gzipped ember.min.js from 2 years ago
- when gzipped, those two files will swap which is the smallest file

**Comment by ilkkao** [comment]
You are right, every serious developer will enable gzip. 

I'm thinking of adding second data set to every graph to show the gzipped size. I just checked that github has gzip enabled so the script doesn't need to do compression locally. It can simply assert that 
`Content-Encoding:gzip` in response exists. Content-Length will then reveal transmitted bytes.

I'll add this in near future. PRs also welcome.

**Comment by ilkkao** [comment]
Pushed some commits. Gzipped file sizes are now visible.

**Comment by eliotsykes** [comment]
Amazing, looks fantastic
