### ISSUE TITLE
Use same timescale for all graphs.

### ISSUE THREAD

**Issue by rwjblue** [ilkkao/ember-size-tracker#4]
It is somewhat confusing that the three channels all cover different time ranges.
- Release goes back to 2012-09
- Beta goes back to 2014-07
- Canary goes back to 2015-05

I'm not sure what the best solution is, just figured I'd mention it to see what you thought...

---

This is an **awesome** project, thank you!!!!!!!!!!!!

**Comment by ilkkao** [comment]
Nice to hear.

Currently the unit of x-axis is a release. I've been thinking that at least that needs to be fixed. x-axis should show linear time with nicely spaced labels.

I think it might make most sense to use the ~2 month timescale both for betas and canaries. And longer 2-3 year timescale for stable releases.

Beta & canary charts would then show better if recent changes have had impact on size. Release chart would keep recording the overall trend.

Additional opinions welcome.

**Comment by ilkkao** [comment]
Updated the charts. As an experiment stable releases are tracked last 3 years, beta and canary last 2 months. X-axis is now linear time.

**Comment by ilkkao** [comment]
I think the new times work decently. There's not much extra value to record canary and beta sizes beyond 2 months.
